# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('address', models.CharField(max_length=250, null=True)),
                ('lat', models.IntegerField(default=0)),
                ('lng', models.IntegerField(default=0)),
            ],
        ),
    ]
