# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20171004_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='farebase_uid',
            new_name='firebase_uid',
        ),
    ]
